### ISSUE TITLE
Problem in Injecting Module ngSelect

### ISSUE THREAD

**Issue by suraj740** [pc035860/ngSelect#17]
After installing bower package succesfully and when i am trying to inject ngSelect module, its gives an error that,  the module you are trying to inject is not available .
So if anyone has solution then help me in solving this issue.

**Comment by pc035860** [comment]
@suraj740 Have you include the script from bower package in your HTML?

For example

```html
<script src="bower_components/ngSelect/ngSelect.min.js"></script>
```

**Comment by suraj740** [comment]
ya i have installed bower package and included script also.
